import Head from "next/head";
import HomePage from "./homepage";
import Login from "./Login";
import { useSession} from "next-auth/react"

export default function Home() {
  const { data: session } = useSession()
  return (
    <div>
      <Head>
        <title>MERN TODO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {session ? <HomePage /> : <Login />}
    </div>
  );
}
